[package]
name = "bender_job"
version = "0.1.0"
authors = ["David Huss <dh@widerstandzwecklos.at>"]

[lib]
name = "bender_job"
path = "src/lib.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
failure = "0.1.2"
failure_derive = "0.1.2"