[package]
name = "job"
version = "0.1.0"
authors = ["David Huss <dh@widerstandzwecklos.at>"]

[lib]
name = "job"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }