[package]
name = "bender_job"
version = "0.1.0"
authors = ["David Huss <dh@widerstandzwecklos.at>"]

[lib]
name = "bender_job"
path = "src/lib.rs"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.5.5"
tempfile = "3"
regex = "1"
lazy_static = "1"
bender_bouncer = { git = "ssh://git@code.hfbk.net:4242/bendercode/bender-bouncer.git" }
bender_config = { git = "ssh://git@code.hfbk.net:4242/bendercode/bender-config.git" }
